name: Whitesource Unified Agent Scan

on:
  push:
    branches: [ ua-scan ]

jobs:

  build:
    env:
      WS_APIKEY: ${{secrets.APIKEY}}
      WS_USERKEY: ${{secrets.USERKEY}}
      WS_WSS_URL: https://saas.whitesourcesoftware.com/agent
      WS_PRODUCTNAME: ${{github.event.repository.name}}
      WS_PROJECTNAME: ${{github.ref}}
      WS_FILESYSTEMSCAN: false
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Download RPMs
      run: |
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.23.rpm
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.12.rpm
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.4.2.rpm
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.8.23.rpm
        wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.8.12.rpm


    - name: WhiteSource Unified Agent Scan
      env:
        WS_APIKEY: ${{secrets.APIKEY}}
        WS_USERKEY: ${{secrets.USERKEY}}
        WS_WSS_URL: https://saas.whitesourcesoftware.com/agent
        WS_PRODUCTNAME: ${{github.event.repository.name}}
        WS_PROJECTNAME: ${{github.ref}}
        WS_FILESYSTEMSCAN: false
      run: |
        echo Downloading WhiteSource Unified Agent
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
          echo "Integrity Check Failed"
        else
          echo "Integrity Check Passed"
          echo Starting WhiteSource Scan
          java -jar wss-unified-agent.jar
        fi